### ISSUE TITLE
different styles to set containers dimensions

### ISSUE THREAD

**Issue by stratboy** [mreq/slick-lightbox#55]
Hi, thank you for your code.

I just faced a problem where I needed to use the lightbox on a page with fixed header, and needed to keep the header visible.

Solution was something like this:

``` scss
.slick-lightbox,
.slick-lightbox-inner{
  top: map-get($large, header-height); // move the top
   // reset dimensions
  width: auto;
  height: auto;
  // make fullscreen again, but with real space
  bottom: 0;
  right: 0;
}
```

By only moving the top, you'll end up with uncentered images, because width/height 100% makes the container still as big as the whole window. Instead, we need them to be as the window-top. In other words, the real available space. This is achieved by using top/bottom props on container (and resetting width/height).

I currently tested this solution in ff, chrome, safari, android. IE not yet.

If you'd like, I could test on IE, make the mods to your css, and send you a pull request.

Regards
